version: '3.8'

services:
  video_processor:
    build: .
    container_name: video_proccessor
    ports:
      - "8501:8501"
    # Không cần volume mapping local nữa vì người dùng upload trực tiếp
    # Restart policy giúp container tự khởi động lại nếu có lỗi
    restart: unless-stopped
